### ISSUE TITLE
segmentation

### ISSUE THREAD

**Issue by JavierClearImageAI** [sohailahmedkhan173/Flood-Detection-from-Images-using-Deep-Learning#1]
Thanks for the repo.

The paper performs Semantic Segmentation as well as image classification, while you do image classification only.  Did you manage to perform Semantic segmentation as well or should I start a new project to get that done? 

Also, when trained again I don't get the same values on evaluation:

```
Precision:  0.8
F1 Score:  0.888888888888889
Accuracy:  0.9014084507042254
```

Nevertheless, using your model it works as you said :)

**Comment by sohailahmedkhan** [comment]
Hi, 

Thank you for reaching out. I did this project a while ago.The implementation is just for classification and not for segmentation. I am afraid you have to do segmentation yourself.
